#!/usr/bin/perl

use strict;

die 'MLS_DB_HOST must be set' if (!$ENV{MLS_DB_HOST});

my $force = $ARGV[0] eq '-f';

# sleep for 10 minutes then wake up and check if its time to run

while (1 && !$force) {
    my ($sec, $min, $hour) = localtime(time);

    if ($ENV{MLS_DB_HOST} =~ /^east/ && $hour == 6) {
        # 6am utc = 2am EDT/3am EST
        last;
    }

    elsif ($ENV{MLS_DB_HOST} =~ /^west/ && $hour == 9) {
        # 9am utc = 2am PDT/3am PST
        last;
    }

    sleep 600;
}

print "starting backup...\n";

my $tools = {
    POSTGRES_TOOLS_TCP_ADDR => 'leadable-tools-db.cloudapp.net',
    POSTGRES_TOOLS_TCP_PORT => '6432',
    POSTGRES_TOOLS_USER     => 'tools-db-owner',
    POSTGRES_TOOLS_PASS     => 'zmWWhBDcusTvtq4Bbx5tQW9GAUSMhR3RuyAnghgV',
};
my @tools_env = map {"-e $_='$tools->{$_}'"} keys %$tools;

my $containers = `docker ps | egrep -o 'mls-db-\\w+'`;
my @dbs = split "\n", $containers;

foreach my $db (@dbs) {
    $db =~ /mls-db-(\w+)/;
    my $mls = $1;

    print "pg_dumpall [$mls]\n";

    # /mnt/backup_staging is mapped to /opt/backup in mls-db-*
    my @cmd = (
        q|docker|,
        q|exec|,
        qq|$db|,
        q|pg_dumpall|,
        q|-U mls-db-owner|,
        q|-l mls-db-owner|,
        qq|-f /opt/backup/$mls.sql|,
    );

    `@cmd`;
    `sudo gzip -f /mnt/backup_staging/$mls.sql`;

    print "uploading backup...\n";

    @cmd = (
        q|sudo docker run|,
        @tools_env,
        qq|-e BACKUP_FILE='/opt/backups/$mls.sql.gz'|,
        qq|-e MLS_DB_HOST='$ENV{MLS_DB_HOST}'|,
        qq|-e MLS_NAME='$mls'|,
        q|-v ~/mls-feeds/:/opt/mls-feeds|,
        q|-v /mnt/backup_staging/:/opt/backups|,
        qq|--name=mls-backup-$mls|,
        q|--rm|,
        q|leadable/mls-feeds|,
        qq|perl /opt/mls-feeds/sql/bin/store_backup.pl|,
    );

    `@cmd`;

    print "[$mls] DONE\n";
}

print "backup finished, going back to sleep\n";

# sleep 1 hour before exiting so this doesn't run again until tomorrow
sleep 3600;

exit;

1;
