#!/usr/bin/perl

use FindBin;
use Data::Dumper;

die ".cancel file present in service directory, not starting until it is removed" if (-e "$FindBin::Bin/.cancel");

die "MLS_DB_HOST not set" if (!$ENV{MLS_DB_HOST});

die "MLS_NAME not set" if (!$ENV{MLS_NAME});

my $mls = $ENV{MLS_NAME};

my $db_vars_hash = {
    'east-1' => {
        POSTGRES_PORT_5432_TCP_ADDR => '10.0.0.5', # leadable-mls-feeds-db-1.cloudapp.net
        POSTGRES_PORT_5432_TCP_PORT => '6432',
        POSTGRES_FEEDS_USER     => 'mls-db-owner',
        POSTGRES_FEEDS_PASS     => 'zmWWhBDcusTvtq4Bbx5tQW9GAUSMhR3RuyAnghgV',
    },
    'west-1' => {
        POSTGRES_PORT_5432_TCP_ADDR => '10.5.0.5', # leadable-feeds-live-db-west-1.cloudapp.net
        POSTGRES_PORT_5432_TCP_PORT => '6432',
        POSTGRES_FEEDS_USER     => 'mls-db-owner',
        POSTGRES_FEEDS_PASS     => 'zmWWhBDcusTvtq4Bbx5tQW9GAUSMhR3RuyAnghgV',
    },
};

my $tools = {
    POSTGRES_TOOLS_TCP_ADDR => 'leadable-tools-db.cloudapp.net',
    POSTGRES_TOOLS_TCP_PORT => '6432',
    POSTGRES_TOOLS_USER     => 'tools-db-owner',
    POSTGRES_TOOLS_PASS     => 'zmWWhBDcusTvtq4Bbx5tQW9GAUSMhR3RuyAnghgV',
};

sub is_container_running {
    my $label = shift;

    return `sudo docker inspect --format="{{ .State.Running }}" $label` eq "true\n";
}

my $env_vars = $db_vars_hash->{$ENV{MLS_DB_HOST}};

die "[$env_vars] not found in db_vars_hash" if (!$env_vars);

my @tools_env = map {"-e $_='$tools->{$_}'"} keys %$tools;
my @live_env  = map {"-e $_='$env_vars->{$_}'"} keys %$env_vars;

my $pid = fork;
if (! defined $pid) {
    die "Error forking\n";
}
elsif ($pid == 0) {
    # note: on local machines, run this command without sudo
    my @cmd = (
        q|sudo docker run|,
        @tools_env,
        @live_env,
        q|-v /home/joe/mls-feeds/:/opt/mls-feeds|,
        qq|--name=mls-feeds-$mls|,
        q|--rm|,
        q|leadable/mls-feeds|,
        qq|perl /opt/mls-feeds/bin/resource/run.pl -b $mls|,
    );

    `@cmd`;

    exit;
}
else {
    # parent: poll periodically for status file
    while (1) {
        sleep 10;

        # check for cancel file
        if (-e "$FindBin::Bin/.cancel") {
            print "Cancel file found while running [$mls]\n";
            `sudo svc -d $FindBin::Bin`;
            `sudo docker stop mls-feeds-$mls`;
            exit;
        }
        elsif (! is_container_running("mls-feeds-$mls")) {
            # docker process ended
            print "[$mls] finished ok\n";
            last;
        }
    }
}

exit 0;
