#!/usr/bin/perl

use FindBin;
use Data::Dumper;

die ".cancel file present in service directory, not starting until it is removed" if (-e "$FindBin::Bin/.cancel");

die 'MLS_DB_HOST must be set'  if (!$ENV{MLS_DB_HOST});
die 'MLS_TIMEZONE must be set' if (!$ENV{MLS_TIMEZONE});

die "MLS_NAME not set" if (!$ENV{MLS_NAME});

my $mls = $ENV{MLS_NAME};

my $tools = {
    POSTGRES_TOOLS_TCP_ADDR => 'leadable-tools-db.cloudapp.net',
    POSTGRES_TOOLS_TCP_PORT => '6432',
    POSTGRES_TOOLS_USER     => 'tools-db-owner',
    POSTGRES_TOOLS_PASS     => 'zmWWhBDcusTvtq4Bbx5tQW9GAUSMhR3RuyAnghgV',
};

my $feeds = {
    POSTGRES_FEEDS_USER     => 'mls-db-owner',
    POSTGRES_FEEDS_PASS     => 'zmWWhBDcusTvtq4Bbx5tQW9GAUSMhR3RuyAnghgV',
};

sub is_container_running {
    my $label = shift;

    return `docker inspect --format="{{ .State.Running }}" $label` eq "true\n";
}

# cleanup old containers, not always removed by docker for some reason
`docker rm -f mls-feeds-$mls`;

my @tools_env = map {"-e $_='$tools->{$_}'"} keys %$tools;
my @live_env  = map {"-e $_='$feeds->{$_}'"} keys %$feeds;

my @params_list;
if (-e "$FindBin::Bin/params") {
    # each line of the params file will be what is executed
    open(my $fh, '<', "$FindBin::Bin/params") or
        die "Could not open [$FindBin::Bin/params]: $!";

    while (<$fh>) {
        chomp;
        push @params_list, $_;
    }
}
else {
    # default to just running Property
    push @params_list, '-r Property';
}

my $start_time = time;

foreach my $params (@params_list) {
    my $pid = fork;
    if (! defined $pid) {
        die "Error forking\n";
    }
    elsif ($pid == 0) {
        # note: on local machines, run this command without sudo
        my @cmd = (
            q|docker run|,
            @tools_env,
            @live_env,
            qq|-e MLS_DB_HOST='$ENV{MLS_DB_HOST}'|,
            qq|-e MLS_TIMEZONE='$ENV{MLS_TIMEZONE}'|,
            qq|--link mls-db-beaches:postgres|,
            q|--privileged|,
            q|-v ~/mls-feeds/:/opt/mls-feeds|,
            qq|--name=mls-feeds-$mls|,
            q|--rm|,
            q|leadable/mls-feeds|,
            qq|perl /opt/mls-feeds/bin/resource/run.pl -b $mls $params|,
        );

        `@cmd`;

        exit;
    }
    else {
        # parent: poll periodically for status file
        while (1) {
            sleep 10;

            # check for cancel file
            if (-e "$FindBin::Bin/.cancel") {
                print "Cancel file found while running [$mls]\n";
                `docker stop mls-feeds-$mls`;
                exit;
            }
            elsif (! is_container_running("mls-feeds-$mls")) {
                # docker process ended
                print "[$mls $params] finished ok\n";
                last;
            }
        }
    }
}

# sleep until this script has been running for at least 5 minutes total
while (time - $start_time < 300) {
    sleep 1;
}

exit 0;
