DROP VIEW IF EXISTS wiregrass.view_property CASCADE;
CREATE OR REPLACE VIEW wiregrass.view_property AS
SELECT
  'wiregrass'::text as mls,
  __removed_at,
  (__removed_at is null) as __active,
  __class_name,
  (__inserted_at - '1 hours'::interval) as age,
  __inserted_at,
  __modified_at,
  __price_updated_at,
  __price_history_times,
  __price_history_vals,
  __percent_reduced,
  __geo_geom,
  __geo_outlier,
  __status_updated_at,
  __status_history_times,
  __status_history_vals,
  __photo_urls,
  "L_ListingID"::text as listing_id,
  "L_ListingID" as mlsnum,
  "L_Status" as status,
  null::numeric as sold_price,
  null::text as sold_date,
  false as under_contract,
  null::text as under_contract_description,
  "L_AskingPrice" as price,
  coalesce(__image_count, "L_PictureCount"::integer, 0) as image_count,
  "LM_Int1_1" as beds,
  'for_sale'::text as listing_type,
  CASE __class_name
    WHEN 'LD_2' THEN 'Lots & Land'
    WHEN 'CI_3' THEN 'Commericial'
    WHEN 'RE_1' THEN "L_Type_"
    WHEN 'MF_4' THEN 'Multi-Family'
  END as type,
  "LM_Int2_8" as baths_total,
  "LR_remarks22" as remarks,
  initcap("L_Address") as address_line1,
  initcap("L_City") as city,
  initcap("L_City") || ', ' || "L_State" as city_st,
  "L_Zip" as zip,
  "L_State" as state,
  initcap("L_City") || ', ' || "L_State" || ' ' || "L_Zip" as address_line2,
  initcap("L_Area") as county,
  __geo_modified_at,
  __geo_latitude as latitude,
  __geo_longitude as longitude,
  "L_SquareFeet" as square_feet,
  "LM_Int4_1" as year_built,
  "L_NumAcres" as acres,
  "LFD_BASEMENT_16" is not null as "basement",
  "LFD_FIREPLACE_7" is not null as "fireplace",
  coalesce('Ranch Rambler' = ANY ("LFD_STYLE_18"), 'f'::boolean) as "ranch_style",
  "LFD_POOL_23" is not null as "pool",
  coalesce("LFD_PATIO_109","LFD_PATIO_142","LFD_PATIO_24") is not null as "patio_deck_porch",
  coalesce("LFD_ADDITIONALAMENITIES_118") as "feature_additionalamenities[]",
  coalesce("LFD_APPLIANCES_10","LFD_APPLIANCES_128","LFD_APPLIANCES_95") as "feature_appliances[]",
  coalesce("LFD_ATTIC_107","LFD_ATTIC_22") as "feature_attic[]",
  coalesce("LFD_BASEMENT_101","LFD_BASEMENT_134","LFD_BASEMENT_16") as "feature_basement[]",
  coalesce("LFD_BATHROOMINFO_111","LFD_BATHROOMINFO_144","LFD_BATHROOMINFO_26") as "feature_bathroominfo[]",
  coalesce("LFD_BEDROOMINFO_110","LFD_BEDROOMINFO_143","LFD_BEDROOMINFO_25") as "feature_bedroominfo[]",
  coalesce("LFD_CONSTRUCTION_46") as "feature_construction[]",
  coalesce("LFD_COOLING_120","LFD_COOLING_2","LFD_COOLING_48","LFD_COOLING_87") as "feature_cooling[]",
  coalesce("LFD_DININGROOMTYPE_127","LFD_DININGROOMTYPE_9","LFD_DININGROOMTYPE_94") as "feature_diningroomtype[]",
  coalesce("LFD_DOCUMENTSONFILE_112","LFD_DOCUMENTSONFILE_27","LFD_DOCUMENTSONFILE_39","LFD_DOCUMENTSONFILE_52") as "feature_documentsonfile[]",
  coalesce("LFD_ELECTRIC_38","LFD_ELECTRIC_49") as "feature_electric[]",
  coalesce("LFD_ELECTRICAUTHORITY_123","LFD_ELECTRICAUTHORITY_40","LFD_ELECTRICAUTHORITY_5","LFD_ELECTRICAUTHORITY_53","LFD_ELECTRICAUTHORITY_90") as "feature_electricauthority[]",
  coalesce("LFD_EXTERIOR_14","LFD_EXTERIOR_99") as "feature_exterior[]",
  coalesce("LFD_EXTRAROOMS_126","LFD_EXTRAROOMS_8","LFD_EXTRAROOMS_93") as "feature_extrarooms[]",
  coalesce("LFD_EXTRAS_11","LFD_EXTRAS_129","LFD_EXTRAS_50","LFD_EXTRAS_96") as "feature_extras[]",
  coalesce("LFD_FENCE_102","LFD_FENCE_135","LFD_FENCE_17","LFD_FENCE_33") as "feature_fence[]",
  coalesce("LFD_FIREPLACE_125","LFD_FIREPLACE_7","LFD_FIREPLACE_92") as "feature_fireplace[]",
  coalesce("LFD_FLOORCOVERING_104","LFD_FLOORCOVERING_137","LFD_FLOORCOVERING_19") as "feature_floorcovering[]",
  coalesce("LFD_FOUNDATION_100","LFD_FOUNDATION_15") as "feature_foundation[]",
  coalesce("LFD_GAS_37") as "feature_gas[]",
  coalesce("LFD_HEAT_1","LFD_HEAT_119","LFD_HEAT_47","LFD_HEAT_86") as "feature_heat[]",
  coalesce("LFD_IMPROVEMENTS_114","LFD_IMPROVEMENTS_29") as "feature_improvements[]",
  coalesce("LFD_LAUNDRYLOCATION_12","LFD_LAUNDRYLOCATION_130","LFD_LAUNDRYLOCATION_97") as "feature_laundrylocation[]",
  coalesce("LFD_LOTDESCRIPTION_115","LFD_LOTDESCRIPTION_116","LFD_LOTDESCRIPTION_30") as "feature_lotdescription[]",
  coalesce("LFD_PATIO_109","LFD_PATIO_142","LFD_PATIO_24") as "feature_patio[]",
  coalesce("LFD_POOL_108","LFD_POOL_141","LFD_POOL_23") as "feature_pool[]",
  coalesce("LFD_ROADTYPE_36","LFD_ROADTYPE_51") as "feature_roadtype[]",
  coalesce("LFD_ROOF_13","LFD_ROOF_85","LFD_ROOF_98") as "feature_roof[]",
  coalesce("LFD_SEWER_121","LFD_SEWER_3","LFD_SEWER_35","LFD_SEWER_44","LFD_SEWER_88") as "feature_sewer[]",
  coalesce("LFD_SHOWINSTRUCTIONS_113","LFD_SHOWINSTRUCTIONS_146","LFD_SHOWINSTRUCTIONS_28") as "feature_showinstructions[]",
  coalesce("LFD_STYLE_103","LFD_STYLE_18") as "feature_style[]",
  coalesce("LFD_TOPOGRAPHY_31") as "feature_topography[]",
  coalesce("LFD_TRASH_105","LFD_TRASH_138","LFD_TRASH_20") as "feature_trash[]",
  coalesce("LFD_VIEW_32") as "feature_view[]",
  coalesce("LFD_WATER_122","LFD_WATER_34","LFD_WATER_4","LFD_WATER_43","LFD_WATER_89") as "feature_water[]",
  coalesce("LFD_WATERAUTHORITY_124","LFD_WATERAUTHORITY_41","LFD_WATERAUTHORITY_54","LFD_WATERAUTHORITY_6","LFD_WATERAUTHORITY_91") as "feature_waterauthority[]",
  coalesce("LFD_WINDOWS_106","LFD_WINDOWS_21") as "feature_windows[]",
  coalesce("LFD_ZONING_42") as "feature_zoning[]",
  "L_Keyword2" as feature_full_baths,
  "L_Keyword3" as feature_half_baths,
  "L_Keyword5" IN ('Yes', 'Carport Attached', 'Carport Detached', 'Garage Attached', 'Garage Detached', 'Other/See Remarks') as garage,
  "L_Keyword7" as feature_pool,
  "VT_VTourURL" as virtual_tour,
  null::text as __minor_area,
  null::text as __major_area,
  trim(initcap("LM_Char10_14")) as subdivision,
  "L_UpdateDate" as modification_timestamp,
  ("L_IdxInclude" <> 'Yes Without Address') as display_address,
  initcap("LM_Char10_11") as elementary_school,
  initcap("LM_Char10_12") as middle_school,
  initcap("LM_Char10_13") as high_school,
  null::text as school_district,
  initcap("LO1_OrganizationName") as office_name,
  "LM_Dec_13" as feature_pet_fee,
  "LM_Dec_9" as price_per_sqft,
  initcap("L_Type_") as feature_type

FROM wiregrass."Property"
;
