DROP VIEW IF EXISTS realcomp2.view_property CASCADE;
CREATE OR REPLACE VIEW realcomp2.view_property AS
SELECT
  'realcomp2'::text as mls,
  __removed_at,
  (__removed_at IS NULL) as __active,
  __inserted_at as age,
  __inserted_at,
  __modified_at,
  __geo_geom,
  __geo_outlier,
  __price_updated_at,
  "VirtualTourURLUnbranded" as virtual_tour,
  __price_history_times,
  __price_history_vals,
  __percent_reduced,
  __status_updated_at,
  __status_history_times,
  __status_history_vals,
  __geo_places,
  __photo_urls,
  "MLS" as source_mls,
  null::text as __list_date,
  last_transaction_completed_at,
  null::integer as days_to_close,
  null::text as sold_date,
  null::integer as sold_price,
  'for_sale'::text as listing_type,
  "Matrix_Unique_ID" as listing_id,
  "MLSNumber" as mlsnum,
  "Status" as status,
  ("Status" = 'Contingent - Continue To Show') as under_contract,
  CASE "Status"
    WHEN 'Contingent - Continue To Show' THEN 'Under Contract'
    ELSE NULL::text
  END as under_contract_description,
  coalesce(__image_count, "PhotoCount", 0) as image_count,
  "ListPrice" as price,
  "BedsTotal" as beds,
  CASE "PropertyType"
    WHEN 'Condominium' THEN 
      CASE "TransactionType"
        WHEN 'Lease' THEN 'Condo - Rental'
        WHEN 'Sale' THEN 'Condo'
      END
    WHEN 'Residential' THEN 
      CASE "TransactionType"
        WHEN 'Lease' THEN 'Single Family - Rental'
        WHEN 'Sale' THEN 'Single Family'
      END
    WHEN 'Vacant Land' THEN 'Lots & Land'
  END as type,
  "BathsFull" as baths_total,
  "PublicRemarks" as remarks,
  "UnparsedAddress" as address_line1,
  "PostalCity" || ', MI ' || "PostalCode" as address_line2,
  "City" as city,
  'MI'::text as state,
  "City" || ', MI'  as city_st,
  "PostalCode" as zip,
  "CountyOrParish" as county,
  null::text as township,
  __geo_modified_at,
  __geo_latitude as latitude,
  __geo_longitude as longitude,
  "sqftTotal" as square_feet,
  "YearBuilt" as year_built,
  "LotSizeArea" as acres,
  "LotSizeDimensions" as feature_lot_dimensions,
  ("BasementYN") as basement,
  ("FireplaceYN") as fireplace,
  ("ExteriorFeatures" && ARRAY['Fenced']) as fenced_yard,
  "WaterfrontYN" as waterfront,
  'Ranch' = ANY ("ArchitectureStyle") as ranch_style,
  "PoolYN" as pool,
  ("ExteriorFeatures" && ARRAY['Deck', 'Patio', 'Porch']) as patio_deck_porch,
  null::text as walk_in_closets,
  null::text as double_vanity,
  null::text as __minor_area,
  null::text as __major_area,
  "SubdivisionName" as subdivision,
  "MatrixModifiedDT" as modification_timestamp,
  "PermitAddressInternetYN" as display_address,
  "SchoolDistrict" as school_district,
  null::text as elementary_school,
  null::text as middle_school,
  null::text as high_school,
  "GarageYN" as garage,
  --"ListOfficeName" as office_name,
  null::text as complex,
  "Architecture" as "feature_architecture[]",
  "ArchitectureStyle" as "feature_architecture_style",
  "ArchitectureLevel" as "feature_architecture_level[]",
  "AssociationFeeFrequency" as "feature_association_fee_frequency",
  "AssociationFeeIncludes" as "feature_association_fee_includes",
  "AssociationFeeText" as "feature_association_fee_amount",
  "BasementFeatures" as "feature_basement_features[]",
  "BasementType" as "feature_basement_type[]",
  "BathsHalf" as "feature_baths_half",
  "ConstructionFeatures" as "feature_construction_features[]",
  "ConstructionMaterials" as "feature_construction_materials[]",
  "Cooling" as "feature_cooling[]",
  "DepositAmount" as "feature_deposit_amount",
  "Directions" as "feature_directions",
  "ExteriorFeatures" as "feature_exterior_features[]",
  "FireplaceFuel" as "feature_fireplace_fuel[]",
  "FireplaceLocations" as "feature_fireplace_locations[]",
  "FoundationDetails" as "feature_foundation_details[]",
  "GarageFeatures" as "feature_garage_features[]",
  "GarageSize" as "feature_garage_size[]",
  "Heating" as "feature_heating[]",
  "HeatingFuel" as "feature_heating_fuel[]",
  "HomesteadYN" as "feature_homestead_y_n",
  "Improvements" as "feature_improvements[]",
  "InteriorFeatures" as "feature_interior_features[]",
  "IrrigationYN" as "feature_irrigation_y_n",
  "KitchenAppliances" as "feature_kitchen_appliances[]",
  "LandContractYN" as "feature_land_contract_y_n",
  "LandInterestRate" as "feature_land_interest_rate",
  "LandPayment" as "feature_land_payment",
  "LotFeatures" as "feature_lot_features[]",
  "MineralRightsYN" as "feature_mineral_rights_y_n",
  "RoomCount" as "feature_room_count",
  "Settlement" as "feature_settlement",
  "Sewer" as "feature_sewer[]",
  "ShortSale" as "feature_short_sale",
  "WaterHeaterFuel" as "feature_water_heater_fuel[]",
  "WaterSource" as "feature_water_source[]",
  "WaterfrontDescription" as "feature_waterfront_description[]",
  "WaterfrontFeatures" as "feature_waterfront_features[]",
  "WaterfrontName" as lake,
  "YearRemodeled" as "feature_year_remodeled",
  "Zoning" as "feature_zoning[]",
  "sqftTotalBsmt" as "feature_sqft_basement",
  "sqftLowerFloor" as "feature_sqft_lower_floor"
FROM
  realcomp2."Property" p, realcomp2.mutation m
WHERE
  p."Matrix_Unique_ID"::text = m.remote_id AND
  m.last_transaction_completed_at IS NOT NULL AND
  p."StateOrProvince" = 'Michigan' AND p."PermitInternetYN"
;
