# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package librets;
use base qw(Exporter);
use base qw(DynaLoader);
package libretsc;
bootstrap librets;
package librets;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package librets;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package librets;


############# Class : librets::StringVector ##############

package librets::StringVector;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_StringVector(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::StringVector_size;
*empty = *libretsc::StringVector_empty;
*clear = *libretsc::StringVector_clear;
*push = *libretsc::StringVector_push;
*pop = *libretsc::StringVector_pop;
*get = *libretsc::StringVector_get;
*set = *libretsc::StringVector_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_StringVector($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::ByteVector ##############

package librets::ByteVector;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_ByteVector(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::ByteVector_size;
*empty = *libretsc::ByteVector_empty;
*clear = *libretsc::ByteVector_clear;
*push = *libretsc::ByteVector_push;
*pop = *libretsc::ByteVector_pop;
*get = *libretsc::ByteVector_get;
*set = *libretsc::ByteVector_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_ByteVector($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::RetsException ##############

package librets::RetsException;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_RetsException(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_RetsException($self);
        delete $OWNER{$self};
    }
}

*GetName = *libretsc::RetsException_GetName;
*GetMessage = *libretsc::RetsException_GetMessage;
*GetExtendedMessage = *libretsc::RetsException_GetExtendedMessage;
*GetFullReport = *libretsc::RetsException_GetFullReport;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::RetsHttpException ##############

package librets::RetsHttpException;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::RetsException librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_RetsHttpException(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_RetsHttpException($self);
        delete $OWNER{$self};
    }
}

*GetHttpResult = *libretsc::RetsHttpException_GetHttpResult;
*GetMessage = *libretsc::RetsHttpException_GetMessage;
*GetName = *libretsc::RetsHttpException_GetName;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::RetsReplyException ##############

package librets::RetsReplyException;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::RetsException librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_RetsReplyException(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_RetsReplyException($self);
        delete $OWNER{$self};
    }
}

*GetReplyCode = *libretsc::RetsReplyException_GetReplyCode;
*GetMeaning = *libretsc::RetsReplyException_GetMeaning;
*GetExtendedMeaning = *libretsc::RetsReplyException_GetExtendedMeaning;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::LoginResponse ##############

package librets::LoginResponse;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
*GetMemberName = *libretsc::LoginResponse_GetMemberName;
*GetUserInfo = *libretsc::LoginResponse_GetUserInfo;
*GetBroker = *libretsc::LoginResponse_GetBroker;
*GetMetadataVersion = *libretsc::LoginResponse_GetMetadataVersion;
*GetMetadataTimestamp = *libretsc::LoginResponse_GetMetadataTimestamp;
*GetMinMetadataTimestamp = *libretsc::LoginResponse_GetMinMetadataTimestamp;
*GetOfficeList = *libretsc::LoginResponse_GetOfficeList;
*GetBalance = *libretsc::LoginResponse_GetBalance;
*GetTimeout = *libretsc::LoginResponse_GetTimeout;
*GetPasswordExpire = *libretsc::LoginResponse_GetPasswordExpire;
*GetActionUrl = *libretsc::LoginResponse_GetActionUrl;
*GetChangePasswordUrl = *libretsc::LoginResponse_GetChangePasswordUrl;
*GetGetObjectUrl = *libretsc::LoginResponse_GetGetObjectUrl;
*GetLoginUrl = *libretsc::LoginResponse_GetLoginUrl;
*GetLoginCompleteUrl = *libretsc::LoginResponse_GetLoginCompleteUrl;
*GetLogoutUrl = *libretsc::LoginResponse_GetLogoutUrl;
*GetSearchUrl = *libretsc::LoginResponse_GetSearchUrl;
*GetGetMetadataUrl = *libretsc::LoginResponse_GetGetMetadataUrl;
*GetServerInformationUrl = *libretsc::LoginResponse_GetServerInformationUrl;
*GetUpdateUrl = *libretsc::LoginResponse_GetUpdateUrl;
*GetPayloadListUrl = *libretsc::LoginResponse_GetPayloadListUrl;
*GetUserID = *libretsc::LoginResponse_GetUserID;
*GetUserClass = *libretsc::LoginResponse_GetUserClass;
*GetUserLevel = *libretsc::LoginResponse_GetUserLevel;
*GetAgentCode = *libretsc::LoginResponse_GetAgentCode;
*GetBrokerCode = *libretsc::LoginResponse_GetBrokerCode;
*GetBrokerBranch = *libretsc::LoginResponse_GetBrokerBranch;
*GetMetadataID = *libretsc::LoginResponse_GetMetadataID;
*GetWarnPasswordExpirationDays = *libretsc::LoginResponse_GetWarnPasswordExpirationDays;
*GetStandardNamesVersion = *libretsc::LoginResponse_GetStandardNamesVersion;
*GetVendorName = *libretsc::LoginResponse_GetVendorName;
*GetServerProductName = *libretsc::LoginResponse_GetServerProductName;
*GetServerProductVersion = *libretsc::LoginResponse_GetServerProductVersion;
*GetOperatorName = *libretsc::LoginResponse_GetOperatorName;
*GetRoleName = *libretsc::LoginResponse_GetRoleName;
*GetSupportContactInformation = *libretsc::LoginResponse_GetSupportContactInformation;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_LoginResponse(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_LoginResponse($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::CapabilityUrls ##############

package librets::CapabilityUrls;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_CapabilityUrls(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_CapabilityUrls($self);
        delete $OWNER{$self};
    }
}

*SetActionUrl = *libretsc::CapabilityUrls_SetActionUrl;
*GetActionUrl = *libretsc::CapabilityUrls_GetActionUrl;
*SetChangePasswordUrl = *libretsc::CapabilityUrls_SetChangePasswordUrl;
*GetChangePasswordUrl = *libretsc::CapabilityUrls_GetChangePasswordUrl;
*SetGetObjectUrl = *libretsc::CapabilityUrls_SetGetObjectUrl;
*GetGetObjectUrl = *libretsc::CapabilityUrls_GetGetObjectUrl;
*SetLoginUrl = *libretsc::CapabilityUrls_SetLoginUrl;
*GetLoginUrl = *libretsc::CapabilityUrls_GetLoginUrl;
*SetLoginCompleteUrl = *libretsc::CapabilityUrls_SetLoginCompleteUrl;
*GetLoginCompleteUrl = *libretsc::CapabilityUrls_GetLoginCompleteUrl;
*SetLogoutUrl = *libretsc::CapabilityUrls_SetLogoutUrl;
*GetLogoutUrl = *libretsc::CapabilityUrls_GetLogoutUrl;
*SetSearchUrl = *libretsc::CapabilityUrls_SetSearchUrl;
*GetSearchUrl = *libretsc::CapabilityUrls_GetSearchUrl;
*SetGetMetadataUrl = *libretsc::CapabilityUrls_SetGetMetadataUrl;
*GetGetMetadataUrl = *libretsc::CapabilityUrls_GetGetMetadataUrl;
*SetServerInformationUrl = *libretsc::CapabilityUrls_SetServerInformationUrl;
*GetServerInformationUrl = *libretsc::CapabilityUrls_GetServerInformationUrl;
*SetUpdateUrl = *libretsc::CapabilityUrls_SetUpdateUrl;
*GetUpdateUrl = *libretsc::CapabilityUrls_GetUpdateUrl;
*SetPayloadListUrl = *libretsc::CapabilityUrls_SetPayloadListUrl;
*GetPayloadListUrl = *libretsc::CapabilityUrls_GetPayloadListUrl;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::SearchRequest ##############

package librets::SearchRequest;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_SearchRequest(@_);
    bless $self, $pkg if defined($self);
}

*SetStandardNames = *libretsc::SearchRequest_SetStandardNames;
*SetSelect = *libretsc::SearchRequest_SetSelect;
*LIMIT_DEFAULT = *libretsc::SearchRequest_LIMIT_DEFAULT;
*LIMIT_DEFAULT = *libretsc::SearchRequest_LIMIT_DEFAULT;
*LIMIT_NONE = *libretsc::SearchRequest_LIMIT_NONE;
*LIMIT_NONE = *libretsc::SearchRequest_LIMIT_NONE;
*SetLimit = *libretsc::SearchRequest_SetLimit;
*OFFSET_NONE = *libretsc::SearchRequest_OFFSET_NONE;
*OFFSET_NONE = *libretsc::SearchRequest_OFFSET_NONE;
*SetOffset = *libretsc::SearchRequest_SetOffset;
*NO_RECORD_COUNT = *libretsc::SearchRequest_NO_RECORD_COUNT;
*RECORD_COUNT_AND_RESULTS = *libretsc::SearchRequest_RECORD_COUNT_AND_RESULTS;
*RECORD_COUNT_ONLY = *libretsc::SearchRequest_RECORD_COUNT_ONLY;
*SetCountType = *libretsc::SearchRequest_SetCountType;
*DMQL = *libretsc::SearchRequest_DMQL;
*DMQL2 = *libretsc::SearchRequest_DMQL2;
*SetQueryType = *libretsc::SearchRequest_SetQueryType;
*COMPACT = *libretsc::SearchRequest_COMPACT;
*COMPACT_DECODED = *libretsc::SearchRequest_COMPACT_DECODED;
*SetFormatType = *libretsc::SearchRequest_SetFormatType;
*GetQueryString = *libretsc::SearchRequest_GetQueryString;
*SetRestrictedIndicator = *libretsc::SearchRequest_SetRestrictedIndicator;
*SetPayload = *libretsc::SearchRequest_SetPayload;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_SearchRequest($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::SearchRequestAPtr ##############

package librets::SearchRequestAPtr;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_SearchRequestAPtr(@_);
    bless $self, $pkg if defined($self);
}

*__deref__ = *libretsc::SearchRequestAPtr___deref__;
*reset = *libretsc::SearchRequestAPtr_reset;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_SearchRequestAPtr($self);
        delete $OWNER{$self};
    }
}

*SetStandardNames = *libretsc::SearchRequestAPtr_SetStandardNames;
*SetSelect = *libretsc::SearchRequestAPtr_SetSelect;
*swig_LIMIT_DEFAULT_get = *libretsc::SearchRequestAPtr_LIMIT_DEFAULT_get;
*swig_LIMIT_DEFAULT_set = *libretsc::SearchRequestAPtr_LIMIT_DEFAULT_set;
*swig_LIMIT_NONE_get = *libretsc::SearchRequestAPtr_LIMIT_NONE_get;
*swig_LIMIT_NONE_set = *libretsc::SearchRequestAPtr_LIMIT_NONE_set;
*SetLimit = *libretsc::SearchRequestAPtr_SetLimit;
*swig_OFFSET_NONE_get = *libretsc::SearchRequestAPtr_OFFSET_NONE_get;
*swig_OFFSET_NONE_set = *libretsc::SearchRequestAPtr_OFFSET_NONE_set;
*SetOffset = *libretsc::SearchRequestAPtr_SetOffset;
*SetCountType = *libretsc::SearchRequestAPtr_SetCountType;
*SetQueryType = *libretsc::SearchRequestAPtr_SetQueryType;
*SetFormatType = *libretsc::SearchRequestAPtr_SetFormatType;
*GetQueryString = *libretsc::SearchRequestAPtr_GetQueryString;
*SetRestrictedIndicator = *libretsc::SearchRequestAPtr_SetRestrictedIndicator;
*SetPayload = *libretsc::SearchRequestAPtr_SetPayload;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::SearchResultSet ##############

package librets::SearchResultSet;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
*HasNext = *libretsc::SearchResultSet_HasNext;
*GetCount = *libretsc::SearchResultSet_GetCount;
*GetColumns = *libretsc::SearchResultSet_GetColumns;
*GetString = *libretsc::SearchResultSet_GetString;
*SetEncoding = *libretsc::SearchResultSet_SetEncoding;
*GetEncoding = *libretsc::SearchResultSet_GetEncoding;
*HasMaxRows = *libretsc::SearchResultSet_HasMaxRows;
*GetReplyCode = *libretsc::SearchResultSet_GetReplyCode;
*GetReplyText = *libretsc::SearchResultSet_GetReplyText;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_SearchResultSet(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_SearchResultSet($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::SearchResultSetAPtr ##############

package librets::SearchResultSetAPtr;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_SearchResultSetAPtr(@_);
    bless $self, $pkg if defined($self);
}

*__deref__ = *libretsc::SearchResultSetAPtr___deref__;
*reset = *libretsc::SearchResultSetAPtr_reset;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_SearchResultSetAPtr($self);
        delete $OWNER{$self};
    }
}

*HasNext = *libretsc::SearchResultSetAPtr_HasNext;
*GetCount = *libretsc::SearchResultSetAPtr_GetCount;
*GetColumns = *libretsc::SearchResultSetAPtr_GetColumns;
*GetString = *libretsc::SearchResultSetAPtr_GetString;
*SetEncoding = *libretsc::SearchResultSetAPtr_SetEncoding;
*GetEncoding = *libretsc::SearchResultSetAPtr_GetEncoding;
*HasMaxRows = *libretsc::SearchResultSetAPtr_HasMaxRows;
*GetReplyCode = *libretsc::SearchResultSetAPtr_GetReplyCode;
*GetReplyText = *libretsc::SearchResultSetAPtr_GetReplyText;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::UpdateRequest ##############

package librets::UpdateRequest;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_UpdateRequest(@_);
    bless $self, $pkg if defined($self);
}

*GetDelimiter = *libretsc::UpdateRequest_GetDelimiter;
*SetDelimiter = *libretsc::UpdateRequest_SetDelimiter;
*GetAllFields = *libretsc::UpdateRequest_GetAllFields;
*GetField = *libretsc::UpdateRequest_GetField;
*SetField = *libretsc::UpdateRequest_SetField;
*UPDATE_OK = *libretsc::UpdateRequest_UPDATE_OK;
*UPDATE_OK = *libretsc::UpdateRequest_UPDATE_OK;
*AUTO_POPULATE = *libretsc::UpdateRequest_AUTO_POPULATE;
*AUTO_POPULATE = *libretsc::UpdateRequest_AUTO_POPULATE;
*VALIDATE_ONLY = *libretsc::UpdateRequest_VALIDATE_ONLY;
*VALIDATE_ONLY = *libretsc::UpdateRequest_VALIDATE_ONLY;
*GetUpdateType = *libretsc::UpdateRequest_GetUpdateType;
*SetUpdateType = *libretsc::UpdateRequest_SetUpdateType;
*GetValidateFlag = *libretsc::UpdateRequest_GetValidateFlag;
*SetValidateFlag = *libretsc::UpdateRequest_SetValidateFlag;
*GetAllWarnings = *libretsc::UpdateRequest_GetAllWarnings;
*GetWarningResponse = *libretsc::UpdateRequest_GetWarningResponse;
*SetWarningResponse = *libretsc::UpdateRequest_SetWarningResponse;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_UpdateRequest($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::UpdateRequestAPtr ##############

package librets::UpdateRequestAPtr;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_UpdateRequestAPtr(@_);
    bless $self, $pkg if defined($self);
}

*__deref__ = *libretsc::UpdateRequestAPtr___deref__;
*reset = *libretsc::UpdateRequestAPtr_reset;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_UpdateRequestAPtr($self);
        delete $OWNER{$self};
    }
}

*GetDelimiter = *libretsc::UpdateRequestAPtr_GetDelimiter;
*SetDelimiter = *libretsc::UpdateRequestAPtr_SetDelimiter;
*GetAllFields = *libretsc::UpdateRequestAPtr_GetAllFields;
*GetField = *libretsc::UpdateRequestAPtr_GetField;
*SetField = *libretsc::UpdateRequestAPtr_SetField;
*swig_UPDATE_OK_get = *libretsc::UpdateRequestAPtr_UPDATE_OK_get;
*swig_UPDATE_OK_set = *libretsc::UpdateRequestAPtr_UPDATE_OK_set;
*swig_AUTO_POPULATE_get = *libretsc::UpdateRequestAPtr_AUTO_POPULATE_get;
*swig_AUTO_POPULATE_set = *libretsc::UpdateRequestAPtr_AUTO_POPULATE_set;
*swig_VALIDATE_ONLY_get = *libretsc::UpdateRequestAPtr_VALIDATE_ONLY_get;
*swig_VALIDATE_ONLY_set = *libretsc::UpdateRequestAPtr_VALIDATE_ONLY_set;
*GetUpdateType = *libretsc::UpdateRequestAPtr_GetUpdateType;
*SetUpdateType = *libretsc::UpdateRequestAPtr_SetUpdateType;
*GetValidateFlag = *libretsc::UpdateRequestAPtr_GetValidateFlag;
*SetValidateFlag = *libretsc::UpdateRequestAPtr_SetValidateFlag;
*GetAllWarnings = *libretsc::UpdateRequestAPtr_GetAllWarnings;
*GetWarningResponse = *libretsc::UpdateRequestAPtr_GetWarningResponse;
*SetWarningResponse = *libretsc::UpdateRequestAPtr_SetWarningResponse;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::UpdateResponse ##############

package librets::UpdateResponse;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_UpdateResponse(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_UpdateResponse($self);
        delete $OWNER{$self};
    }
}

*GetColumns = *libretsc::UpdateResponse_GetColumns;
*GetEncoding = *libretsc::UpdateResponse_GetEncoding;
*GetErrorFieldName = *libretsc::UpdateResponse_GetErrorFieldName;
*GetErrorNumber = *libretsc::UpdateResponse_GetErrorNumber;
*GetErrorOffset = *libretsc::UpdateResponse_GetErrorOffset;
*GetErrorText = *libretsc::UpdateResponse_GetErrorText;
*GetReplyCode = *libretsc::UpdateResponse_GetReplyCode;
*GetReplyText = *libretsc::UpdateResponse_GetReplyText;
*GetString = *libretsc::UpdateResponse_GetString;
*GetWarningFieldName = *libretsc::UpdateResponse_GetWarningFieldName;
*GetWarningNumber = *libretsc::UpdateResponse_GetWarningNumber;
*GetWarningOffset = *libretsc::UpdateResponse_GetWarningOffset;
*GetWarningResponseRequired = *libretsc::UpdateResponse_GetWarningResponseRequired;
*GetWarningText = *libretsc::UpdateResponse_GetWarningText;
*HasNext = *libretsc::UpdateResponse_HasNext;
*HasNextError = *libretsc::UpdateResponse_HasNextError;
*HasNextWarning = *libretsc::UpdateResponse_HasNextWarning;
*SetEncoding = *libretsc::UpdateResponse_SetEncoding;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::UpdateResponseAPtr ##############

package librets::UpdateResponseAPtr;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_UpdateResponseAPtr(@_);
    bless $self, $pkg if defined($self);
}

*__deref__ = *libretsc::UpdateResponseAPtr___deref__;
*reset = *libretsc::UpdateResponseAPtr_reset;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_UpdateResponseAPtr($self);
        delete $OWNER{$self};
    }
}

*GetColumns = *libretsc::UpdateResponseAPtr_GetColumns;
*GetEncoding = *libretsc::UpdateResponseAPtr_GetEncoding;
*GetErrorFieldName = *libretsc::UpdateResponseAPtr_GetErrorFieldName;
*GetErrorNumber = *libretsc::UpdateResponseAPtr_GetErrorNumber;
*GetErrorOffset = *libretsc::UpdateResponseAPtr_GetErrorOffset;
*GetErrorText = *libretsc::UpdateResponseAPtr_GetErrorText;
*GetReplyCode = *libretsc::UpdateResponseAPtr_GetReplyCode;
*GetReplyText = *libretsc::UpdateResponseAPtr_GetReplyText;
*GetString = *libretsc::UpdateResponseAPtr_GetString;
*GetWarningFieldName = *libretsc::UpdateResponseAPtr_GetWarningFieldName;
*GetWarningNumber = *libretsc::UpdateResponseAPtr_GetWarningNumber;
*GetWarningOffset = *libretsc::UpdateResponseAPtr_GetWarningOffset;
*GetWarningResponseRequired = *libretsc::UpdateResponseAPtr_GetWarningResponseRequired;
*GetWarningText = *libretsc::UpdateResponseAPtr_GetWarningText;
*HasNext = *libretsc::UpdateResponseAPtr_HasNext;
*HasNextError = *libretsc::UpdateResponseAPtr_HasNextError;
*HasNextWarning = *libretsc::UpdateResponseAPtr_HasNextWarning;
*SetEncoding = *libretsc::UpdateResponseAPtr_SetEncoding;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::LogoutResponse ##############

package librets::LogoutResponse;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
*GetBillingInfo = *libretsc::LogoutResponse_GetBillingInfo;
*GetLogoutMessage = *libretsc::LogoutResponse_GetLogoutMessage;
*GetConnectTime = *libretsc::LogoutResponse_GetConnectTime;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_LogoutResponse(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_LogoutResponse($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::LogoutResponseAPtr ##############

package librets::LogoutResponseAPtr;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_LogoutResponseAPtr(@_);
    bless $self, $pkg if defined($self);
}

*__deref__ = *libretsc::LogoutResponseAPtr___deref__;
*reset = *libretsc::LogoutResponseAPtr_reset;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_LogoutResponseAPtr($self);
        delete $OWNER{$self};
    }
}

*GetBillingInfo = *libretsc::LogoutResponseAPtr_GetBillingInfo;
*GetLogoutMessage = *libretsc::LogoutResponseAPtr_GetLogoutMessage;
*GetConnectTime = *libretsc::LogoutResponseAPtr_GetConnectTime;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::GetObjectRequest ##############

package librets::GetObjectRequest;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
*PHOTO_TYPE = *libretsc::GetObjectRequest_PHOTO_TYPE;
*PLAT_TYPE = *libretsc::GetObjectRequest_PLAT_TYPE;
*VIDEO_TYPE = *libretsc::GetObjectRequest_VIDEO_TYPE;
*AUDIO_TYPE = *libretsc::GetObjectRequest_AUDIO_TYPE;
*THUMBNAIL_TYPE = *libretsc::GetObjectRequest_THUMBNAIL_TYPE;
*MAP_TYPE = *libretsc::GetObjectRequest_MAP_TYPE;
*VRIMAGE_TYPE = *libretsc::GetObjectRequest_VRIMAGE_TYPE;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_GetObjectRequest(@_);
    bless $self, $pkg if defined($self);
}

*GetLocation = *libretsc::GetObjectRequest_GetLocation;
*SetLocation = *libretsc::GetObjectRequest_SetLocation;
*AddObject = *libretsc::GetObjectRequest_AddObject;
*AddAllObjects = *libretsc::GetObjectRequest_AddAllObjects;
*SetObjectData = *libretsc::GetObjectRequest_SetObjectData;
*SetIgnoreMalformedHeaders = *libretsc::GetObjectRequest_SetIgnoreMalformedHeaders;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_GetObjectRequest($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::ObjectData ##############

package librets::ObjectData;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
*GetUID = *libretsc::ObjectData_GetUID;
*GetObjectType = *libretsc::ObjectData_GetObjectType;
*GetResourceName = *libretsc::ObjectData_GetResourceName;
*GetResourceID = *libretsc::ObjectData_GetResourceID;
*GetObjectID = *libretsc::ObjectData_GetObjectID;
*GetMimeType = *libretsc::ObjectData_GetMimeType;
*GetIsDefault = *libretsc::ObjectData_GetIsDefault;
*GetObjectModificationTimestamp = *libretsc::ObjectData_GetObjectModificationTimestamp;
*GetModificationTimestamp = *libretsc::ObjectData_GetModificationTimestamp;
*GetOrderHint = *libretsc::ObjectData_GetOrderHint;
*GetDescription = *libretsc::ObjectData_GetDescription;
*GetCaption = *libretsc::ObjectData_GetCaption;
*GetFileSize = *libretsc::ObjectData_GetFileSize;
*GetWidthPix = *libretsc::ObjectData_GetWidthPix;
*GetHeightPix = *libretsc::ObjectData_GetHeightPix;
*GetDuration = *libretsc::ObjectData_GetDuration;
*GetWidthInch = *libretsc::ObjectData_GetWidthInch;
*GetHeightInch = *libretsc::ObjectData_GetHeightInch;
*GetValue = *libretsc::ObjectData_GetValue;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_ObjectData(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_ObjectData($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::ObjectDescriptor ##############

package librets::ObjectDescriptor;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
*GetObjectKey = *libretsc::ObjectDescriptor_GetObjectKey;
*GetObjectId = *libretsc::ObjectDescriptor_GetObjectId;
*GetDescription = *libretsc::ObjectDescriptor_GetDescription;
*GetLocationUrl = *libretsc::ObjectDescriptor_GetLocationUrl;
*GetContentType = *libretsc::ObjectDescriptor_GetContentType;
*GetObjectData = *libretsc::ObjectDescriptor_GetObjectData;
*GetSubDescription = *libretsc::ObjectDescriptor_GetSubDescription;
*GetUID = *libretsc::ObjectDescriptor_GetUID;
*GetRetsReplyCode = *libretsc::ObjectDescriptor_GetRetsReplyCode;
*GetRetsReplyText = *libretsc::ObjectDescriptor_GetRetsReplyText;
*GetWildIndicator = *libretsc::ObjectDescriptor_GetWildIndicator;
*GetPreferred = *libretsc::ObjectDescriptor_GetPreferred;
*GetDataAsString = *libretsc::ObjectDescriptor_GetDataAsString;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_ObjectDescriptor(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_ObjectDescriptor($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::GetObjectResponse ##############

package librets::GetObjectResponse;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
*NextObject = *libretsc::GetObjectResponse_NextObject;
*GetHttpResponse = *libretsc::GetObjectResponse_GetHttpResponse;
*GetErrorText = *libretsc::GetObjectResponse_GetErrorText;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_GetObjectResponse(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_GetObjectResponse($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataElement ##############

package librets::MetadataElement;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
*SYSTEM = *libretsc::MetadataElement_SYSTEM;
*RESOURCE = *libretsc::MetadataElement_RESOURCE;
*CLASS = *libretsc::MetadataElement_CLASS;
*TABLE = *libretsc::MetadataElement_TABLE;
*UPDATE = *libretsc::MetadataElement_UPDATE;
*UPDATE_TYPE = *libretsc::MetadataElement_UPDATE_TYPE;
*OBJECT = *libretsc::MetadataElement_OBJECT;
*SEARCH_HELP = *libretsc::MetadataElement_SEARCH_HELP;
*EDIT_MASK = *libretsc::MetadataElement_EDIT_MASK;
*LOOKUP = *libretsc::MetadataElement_LOOKUP;
*LOOKUP_TYPE = *libretsc::MetadataElement_LOOKUP_TYPE;
*UPDATE_HELP = *libretsc::MetadataElement_UPDATE_HELP;
*VALIDATION_LOOKUP = *libretsc::MetadataElement_VALIDATION_LOOKUP;
*VALIDATION_LOOKUP_TYPE = *libretsc::MetadataElement_VALIDATION_LOOKUP_TYPE;
*VALIDATION_EXTERNAL = *libretsc::MetadataElement_VALIDATION_EXTERNAL;
*VALIDATION_EXTERNAL_TYPE = *libretsc::MetadataElement_VALIDATION_EXTERNAL_TYPE;
*VALIDATION_EXPRESSION = *libretsc::MetadataElement_VALIDATION_EXPRESSION;
*FOREIGN_KEY = *libretsc::MetadataElement_FOREIGN_KEY;
*GetMetadataType = *libretsc::MetadataElement_GetMetadataType;
*GetAttributeNames = *libretsc::MetadataElement_GetAttributeNames;
*GetStringAttribute = *libretsc::MetadataElement_GetStringAttribute;
*GetIntAttribute = *libretsc::MetadataElement_GetIntAttribute;
*GetBoolAttribute = *libretsc::MetadataElement_GetBoolAttribute;
*GetId = *libretsc::MetadataElement_GetId;
*GetLevel = *libretsc::MetadataElement_GetLevel;
*GetPath = *libretsc::MetadataElement_GetPath;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataElement($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataSystem ##############

package librets::MetadataSystem;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*GetSystemID = *libretsc::MetadataSystem_GetSystemID;
*GetSystemDescription = *libretsc::MetadataSystem_GetSystemDescription;
*GetComments = *libretsc::MetadataSystem_GetComments;
*GetMetadataType = *libretsc::MetadataSystem_GetMetadataType;
*GetTimeZoneOffset = *libretsc::MetadataSystem_GetTimeZoneOffset;
*GetMetadataID = *libretsc::MetadataSystem_GetMetadataID;
*GetResourceVersion = *libretsc::MetadataSystem_GetResourceVersion;
*GetResourceDate = *libretsc::MetadataSystem_GetResourceDate;
*GetForeignKeyVersion = *libretsc::MetadataSystem_GetForeignKeyVersion;
*GetForeignKeyDate = *libretsc::MetadataSystem_GetForeignKeyDate;
*GetFilterVersion = *libretsc::MetadataSystem_GetFilterVersion;
*GetFilterDate = *libretsc::MetadataSystem_GetFilterDate;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataSystem(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataSystem($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataForeignKey ##############

package librets::MetadataForeignKey;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*GetID = *libretsc::MetadataForeignKey_GetID;
*GetForeignKeyID = *libretsc::MetadataForeignKey_GetForeignKeyID;
*GetParentResourceID = *libretsc::MetadataForeignKey_GetParentResourceID;
*GetParentClassID = *libretsc::MetadataForeignKey_GetParentClassID;
*GetParentSystemName = *libretsc::MetadataForeignKey_GetParentSystemName;
*GetChildResourceID = *libretsc::MetadataForeignKey_GetChildResourceID;
*GetChildClassID = *libretsc::MetadataForeignKey_GetChildClassID;
*GetChildSystemName = *libretsc::MetadataForeignKey_GetChildSystemName;
*GetConditionalParentField = *libretsc::MetadataForeignKey_GetConditionalParentField;
*GetConditionalParentValue = *libretsc::MetadataForeignKey_GetConditionalParentValue;
*GetMetadataType = *libretsc::MetadataForeignKey_GetMetadataType;
*GetOneToManyFlag = *libretsc::MetadataForeignKey_GetOneToManyFlag;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataForeignKey(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataForeignKey($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataForeignKeyList ##############

package librets::MetadataForeignKeyList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataForeignKeyList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataForeignKeyList_size;
*empty = *libretsc::MetadataForeignKeyList_empty;
*clear = *libretsc::MetadataForeignKeyList_clear;
*push = *libretsc::MetadataForeignKeyList_push;
*pop = *libretsc::MetadataForeignKeyList_pop;
*get = *libretsc::MetadataForeignKeyList_get;
*set = *libretsc::MetadataForeignKeyList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataForeignKeyList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataResource ##############

package librets::MetadataResource;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*GetId = *libretsc::MetadataResource_GetId;
*GetResourceID = *libretsc::MetadataResource_GetResourceID;
*GetStandardName = *libretsc::MetadataResource_GetStandardName;
*GetKeyField = *libretsc::MetadataResource_GetKeyField;
*GetMetadataType = *libretsc::MetadataResource_GetMetadataType;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataResource(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataResource($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataResourceList ##############

package librets::MetadataResourceList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataResourceList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataResourceList_size;
*empty = *libretsc::MetadataResourceList_empty;
*clear = *libretsc::MetadataResourceList_clear;
*push = *libretsc::MetadataResourceList_push;
*pop = *libretsc::MetadataResourceList_pop;
*get = *libretsc::MetadataResourceList_get;
*set = *libretsc::MetadataResourceList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataResourceList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataClass ##############

package librets::MetadataClass;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*GetId = *libretsc::MetadataClass_GetId;
*GetClassName = *libretsc::MetadataClass_GetClassName;
*GetStandardName = *libretsc::MetadataClass_GetStandardName;
*GetDescription = *libretsc::MetadataClass_GetDescription;
*GetMetadataType = *libretsc::MetadataClass_GetMetadataType;
*GetVisibleName = *libretsc::MetadataClass_GetVisibleName;
*GetTableVersion = *libretsc::MetadataClass_GetTableVersion;
*GetTableDate = *libretsc::MetadataClass_GetTableDate;
*GetUpdateVersion = *libretsc::MetadataClass_GetUpdateVersion;
*GetUpdateDate = *libretsc::MetadataClass_GetUpdateDate;
*GetClassTimeStamp = *libretsc::MetadataClass_GetClassTimeStamp;
*GetDeletedFlagField = *libretsc::MetadataClass_GetDeletedFlagField;
*GetDeletedFlagValue = *libretsc::MetadataClass_GetDeletedFlagValue;
*HasKeyIndex = *libretsc::MetadataClass_HasKeyIndex;
*HasOffsetSupport = *libretsc::MetadataClass_HasOffsetSupport;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataClass(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataClass($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataClassList ##############

package librets::MetadataClassList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataClassList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataClassList_size;
*empty = *libretsc::MetadataClassList_empty;
*clear = *libretsc::MetadataClassList_clear;
*push = *libretsc::MetadataClassList_push;
*pop = *libretsc::MetadataClassList_pop;
*get = *libretsc::MetadataClassList_get;
*set = *libretsc::MetadataClassList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataClassList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataTable ##############

package librets::MetadataTable;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*BOOLEAN = *libretsc::MetadataTable_BOOLEAN;
*CHARACTER = *libretsc::MetadataTable_CHARACTER;
*DATE = *libretsc::MetadataTable_DATE;
*DATE_TIME = *libretsc::MetadataTable_DATE_TIME;
*TIME = *libretsc::MetadataTable_TIME;
*TINY = *libretsc::MetadataTable_TINY;
*SMALL = *libretsc::MetadataTable_SMALL;
*INT = *libretsc::MetadataTable_INT;
*LONG = *libretsc::MetadataTable_LONG;
*DECIMAL = *libretsc::MetadataTable_DECIMAL;
*NUMBER = *libretsc::MetadataTable_NUMBER;
*CURRENCY = *libretsc::MetadataTable_CURRENCY;
*LOOKUP = *libretsc::MetadataTable_LOOKUP;
*LOOKUP_MULTI = *libretsc::MetadataTable_LOOKUP_MULTI;
*LOOKUP_BITSTRING = *libretsc::MetadataTable_LOOKUP_BITSTRING;
*LOOKUP_BITMASK = *libretsc::MetadataTable_LOOKUP_BITMASK;
*NO_INTERPRETATION = *libretsc::MetadataTable_NO_INTERPRETATION;
*LEFT = *libretsc::MetadataTable_LEFT;
*RIGHT = *libretsc::MetadataTable_RIGHT;
*CENTER = *libretsc::MetadataTable_CENTER;
*JUSTIFY = *libretsc::MetadataTable_JUSTIFY;
*NO_ALIGNMENT = *libretsc::MetadataTable_NO_ALIGNMENT;
*FEET = *libretsc::MetadataTable_FEET;
*METERS = *libretsc::MetadataTable_METERS;
*SQUARE_FEET = *libretsc::MetadataTable_SQUARE_FEET;
*SQUARE_METERS = *libretsc::MetadataTable_SQUARE_METERS;
*ACRES = *libretsc::MetadataTable_ACRES;
*HECTARES = *libretsc::MetadataTable_HECTARES;
*NO_UNITS = *libretsc::MetadataTable_NO_UNITS;
*UPPER = *libretsc::MetadataTable_UPPER;
*LOWER = *libretsc::MetadataTable_LOWER;
*EXACT = *libretsc::MetadataTable_EXACT;
*MIXED = *libretsc::MetadataTable_MIXED;
*NO_CASE = *libretsc::MetadataTable_NO_CASE;
*GetSystemName = *libretsc::MetadataTable_GetSystemName;
*GetStandardName = *libretsc::MetadataTable_GetStandardName;
*GetLongName = *libretsc::MetadataTable_GetLongName;
*GetDBName = *libretsc::MetadataTable_GetDBName;
*GetShortName = *libretsc::MetadataTable_GetShortName;
*GetMaximumLength = *libretsc::MetadataTable_GetMaximumLength;
*GetDataType = *libretsc::MetadataTable_GetDataType;
*GetPrecision = *libretsc::MetadataTable_GetPrecision;
*IsSearchable = *libretsc::MetadataTable_IsSearchable;
*GetInterpretation = *libretsc::MetadataTable_GetInterpretation;
*GetAlignment = *libretsc::MetadataTable_GetAlignment;
*UseSeparator = *libretsc::MetadataTable_UseSeparator;
*GetEditMaskId = *libretsc::MetadataTable_GetEditMaskId;
*GetLookupName = *libretsc::MetadataTable_GetLookupName;
*GetMaxSelect = *libretsc::MetadataTable_GetMaxSelect;
*GetUnits = *libretsc::MetadataTable_GetUnits;
*GetIndex = *libretsc::MetadataTable_GetIndex;
*GetMinimum = *libretsc::MetadataTable_GetMinimum;
*GetMinimumAsString = *libretsc::MetadataTable_GetMinimumAsString;
*GetMaximum = *libretsc::MetadataTable_GetMaximum;
*GetMaximumAsString = *libretsc::MetadataTable_GetMaximumAsString;
*GetDefault = *libretsc::MetadataTable_GetDefault;
*GetRequired = *libretsc::MetadataTable_GetRequired;
*GetSearchHelpId = *libretsc::MetadataTable_GetSearchHelpId;
*GetMetadataType = *libretsc::MetadataTable_GetMetadataType;
*IsUnique = *libretsc::MetadataTable_IsUnique;
*InKeyIndex = *libretsc::MetadataTable_InKeyIndex;
*GetFilterParentField = *libretsc::MetadataTable_GetFilterParentField;
*GetDefaultSearchOrder = *libretsc::MetadataTable_GetDefaultSearchOrder;
*GetCase = *libretsc::MetadataTable_GetCase;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataTable(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataTable($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataTableList ##############

package librets::MetadataTableList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataTableList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataTableList_size;
*empty = *libretsc::MetadataTableList_empty;
*clear = *libretsc::MetadataTableList_clear;
*push = *libretsc::MetadataTableList_push;
*pop = *libretsc::MetadataTableList_pop;
*get = *libretsc::MetadataTableList_get;
*set = *libretsc::MetadataTableList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataTableList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataLookup ##############

package librets::MetadataLookup;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*GetId = *libretsc::MetadataLookup_GetId;
*GetLookupName = *libretsc::MetadataLookup_GetLookupName;
*GetVisibleName = *libretsc::MetadataLookup_GetVisibleName;
*GetVersion = *libretsc::MetadataLookup_GetVersion;
*GetDate = *libretsc::MetadataLookup_GetDate;
*GetMetadataType = *libretsc::MetadataLookup_GetMetadataType;
*GetFilterID = *libretsc::MetadataLookup_GetFilterID;
*GetNotShownByDefault = *libretsc::MetadataLookup_GetNotShownByDefault;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataLookup(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataLookup($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataLookupList ##############

package librets::MetadataLookupList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataLookupList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataLookupList_size;
*empty = *libretsc::MetadataLookupList_empty;
*clear = *libretsc::MetadataLookupList_clear;
*push = *libretsc::MetadataLookupList_push;
*pop = *libretsc::MetadataLookupList_pop;
*get = *libretsc::MetadataLookupList_get;
*set = *libretsc::MetadataLookupList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataLookupList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataLookupType ##############

package librets::MetadataLookupType;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*GetId = *libretsc::MetadataLookupType_GetId;
*GetValue = *libretsc::MetadataLookupType_GetValue;
*GetLongValue = *libretsc::MetadataLookupType_GetLongValue;
*GetShortValue = *libretsc::MetadataLookupType_GetShortValue;
*GetMetadataType = *libretsc::MetadataLookupType_GetMetadataType;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataLookupType(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataLookupType($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataLookupTypeList ##############

package librets::MetadataLookupTypeList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataLookupTypeList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataLookupTypeList_size;
*empty = *libretsc::MetadataLookupTypeList_empty;
*clear = *libretsc::MetadataLookupTypeList_clear;
*push = *libretsc::MetadataLookupTypeList_push;
*pop = *libretsc::MetadataLookupTypeList_pop;
*get = *libretsc::MetadataLookupTypeList_get;
*set = *libretsc::MetadataLookupTypeList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataLookupTypeList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataObject ##############

package librets::MetadataObject;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*GetId = *libretsc::MetadataObject_GetId;
*GetObjectType = *libretsc::MetadataObject_GetObjectType;
*GetMIMEType = *libretsc::MetadataObject_GetMIMEType;
*GetVisibleName = *libretsc::MetadataObject_GetVisibleName;
*GetDescription = *libretsc::MetadataObject_GetDescription;
*GetMetadataType = *libretsc::MetadataObject_GetMetadataType;
*GetObjectTimeStamp = *libretsc::MetadataObject_GetObjectTimeStamp;
*GetObjectCount = *libretsc::MetadataObject_GetObjectCount;
*GetLocationAvailability = *libretsc::MetadataObject_GetLocationAvailability;
*GetObjectData = *libretsc::MetadataObject_GetObjectData;
*GetMaxFileSize = *libretsc::MetadataObject_GetMaxFileSize;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataObject(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataObject($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataObjectList ##############

package librets::MetadataObjectList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataObjectList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataObjectList_size;
*empty = *libretsc::MetadataObjectList_empty;
*clear = *libretsc::MetadataObjectList_clear;
*push = *libretsc::MetadataObjectList_push;
*pop = *libretsc::MetadataObjectList_pop;
*get = *libretsc::MetadataObjectList_get;
*set = *libretsc::MetadataObjectList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataObjectList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataSearchHelp ##############

package librets::MetadataSearchHelp;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*GetId = *libretsc::MetadataSearchHelp_GetId;
*GetSearchHelpID = *libretsc::MetadataSearchHelp_GetSearchHelpID;
*GetValue = *libretsc::MetadataSearchHelp_GetValue;
*GetMetadataType = *libretsc::MetadataSearchHelp_GetMetadataType;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataSearchHelp(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataSearchHelp($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataSearchHelpList ##############

package librets::MetadataSearchHelpList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataSearchHelpList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataSearchHelpList_size;
*empty = *libretsc::MetadataSearchHelpList_empty;
*clear = *libretsc::MetadataSearchHelpList_clear;
*push = *libretsc::MetadataSearchHelpList_push;
*pop = *libretsc::MetadataSearchHelpList_pop;
*get = *libretsc::MetadataSearchHelpList_get;
*set = *libretsc::MetadataSearchHelpList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataSearchHelpList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataColumnGroup ##############

package librets::MetadataColumnGroup;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*GetMetadataType = *libretsc::MetadataColumnGroup_GetMetadataType;
*GetId = *libretsc::MetadataColumnGroup_GetId;
*GetColumnGroupName = *libretsc::MetadataColumnGroup_GetColumnGroupName;
*GetControlSystemName = *libretsc::MetadataColumnGroup_GetControlSystemName;
*GetLongName = *libretsc::MetadataColumnGroup_GetLongName;
*GetShortName = *libretsc::MetadataColumnGroup_GetShortName;
*GetDescription = *libretsc::MetadataColumnGroup_GetDescription;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataColumnGroup(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataColumnGroup($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataColumnGroupList ##############

package librets::MetadataColumnGroupList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataColumnGroupList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataColumnGroupList_size;
*empty = *libretsc::MetadataColumnGroupList_empty;
*clear = *libretsc::MetadataColumnGroupList_clear;
*push = *libretsc::MetadataColumnGroupList_push;
*pop = *libretsc::MetadataColumnGroupList_pop;
*get = *libretsc::MetadataColumnGroupList_get;
*set = *libretsc::MetadataColumnGroupList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataColumnGroupList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataColumnGroupControl ##############

package librets::MetadataColumnGroupControl;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*GetMetadataType = *libretsc::MetadataColumnGroupControl_GetMetadataType;
*GetId = *libretsc::MetadataColumnGroupControl_GetId;
*GetLowValue = *libretsc::MetadataColumnGroupControl_GetLowValue;
*GetHighValue = *libretsc::MetadataColumnGroupControl_GetHighValue;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataColumnGroupControl(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataColumnGroupControl($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataColumnGrouptControlList ##############

package librets::MetadataColumnGrouptControlList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataColumnGrouptControlList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataColumnGrouptControlList_size;
*empty = *libretsc::MetadataColumnGrouptControlList_empty;
*clear = *libretsc::MetadataColumnGrouptControlList_clear;
*push = *libretsc::MetadataColumnGrouptControlList_push;
*pop = *libretsc::MetadataColumnGrouptControlList_pop;
*get = *libretsc::MetadataColumnGrouptControlList_get;
*set = *libretsc::MetadataColumnGrouptControlList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataColumnGrouptControlList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataColumnGroupNormalization ##############

package librets::MetadataColumnGroupNormalization;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*GetMetadataType = *libretsc::MetadataColumnGroupNormalization_GetMetadataType;
*GetId = *libretsc::MetadataColumnGroupNormalization_GetId;
*GetTypeIdentifier = *libretsc::MetadataColumnGroupNormalization_GetTypeIdentifier;
*GetSequence = *libretsc::MetadataColumnGroupNormalization_GetSequence;
*GetColumnLabel = *libretsc::MetadataColumnGroupNormalization_GetColumnLabel;
*GetSystemName = *libretsc::MetadataColumnGroupNormalization_GetSystemName;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataColumnGroupNormalization(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataColumnGroupNormalization($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataColumnGroupNormalizationList ##############

package librets::MetadataColumnGroupNormalizationList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataColumnGroupNormalizationList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataColumnGroupNormalizationList_size;
*empty = *libretsc::MetadataColumnGroupNormalizationList_empty;
*clear = *libretsc::MetadataColumnGroupNormalizationList_clear;
*push = *libretsc::MetadataColumnGroupNormalizationList_push;
*pop = *libretsc::MetadataColumnGroupNormalizationList_pop;
*get = *libretsc::MetadataColumnGroupNormalizationList_get;
*set = *libretsc::MetadataColumnGroupNormalizationList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataColumnGroupNormalizationList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataColumnGroupSet ##############

package librets::MetadataColumnGroupSet;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*EDIT = *libretsc::MetadataColumnGroupSet_EDIT;
*MATRIX = *libretsc::MetadataColumnGroupSet_MATRIX;
*LIST = *libretsc::MetadataColumnGroupSet_LIST;
*EDIT_LIST = *libretsc::MetadataColumnGroupSet_EDIT_LIST;
*GIS_MAP_SEARCH = *libretsc::MetadataColumnGroupSet_GIS_MAP_SEARCH;
*URL = *libretsc::MetadataColumnGroupSet_URL;
*NO_PRESENTATION = *libretsc::MetadataColumnGroupSet_NO_PRESENTATION;
*GetMetadataType = *libretsc::MetadataColumnGroupSet_GetMetadataType;
*GetId = *libretsc::MetadataColumnGroupSet_GetId;
*GetColumnGroupSetName = *libretsc::MetadataColumnGroupSet_GetColumnGroupSetName;
*GetColumnGroupSetParent = *libretsc::MetadataColumnGroupSet_GetColumnGroupSetParent;
*GetSequence = *libretsc::MetadataColumnGroupSet_GetSequence;
*GetLongName = *libretsc::MetadataColumnGroupSet_GetLongName;
*GetShortName = *libretsc::MetadataColumnGroupSet_GetShortName;
*GetDescription = *libretsc::MetadataColumnGroupSet_GetDescription;
*GetColumnGroupName = *libretsc::MetadataColumnGroupSet_GetColumnGroupName;
*GetPresentationStyle = *libretsc::MetadataColumnGroupSet_GetPresentationStyle;
*GetURL = *libretsc::MetadataColumnGroupSet_GetURL;
*GetForeignKeyID = *libretsc::MetadataColumnGroupSet_GetForeignKeyID;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataColumnGroupSet(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataColumnGroupSet($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataColumnGroupSetList ##############

package librets::MetadataColumnGroupSetList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataColumnGroupSetList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataColumnGroupSetList_size;
*empty = *libretsc::MetadataColumnGroupSetList_empty;
*clear = *libretsc::MetadataColumnGroupSetList_clear;
*push = *libretsc::MetadataColumnGroupSetList_push;
*pop = *libretsc::MetadataColumnGroupSetList_pop;
*get = *libretsc::MetadataColumnGroupSetList_get;
*set = *libretsc::MetadataColumnGroupSetList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataColumnGroupSetList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataColumnGroupTable ##############

package librets::MetadataColumnGroupTable;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
*GetMetadataType = *libretsc::MetadataColumnGroupTable_GetMetadataType;
*GetId = *libretsc::MetadataColumnGroupTable_GetId;
*GetSystemName = *libretsc::MetadataColumnGroupTable_GetSystemName;
*GetColumnGroupSetName = *libretsc::MetadataColumnGroupTable_GetColumnGroupSetName;
*GetLongName = *libretsc::MetadataColumnGroupTable_GetLongName;
*GetShortName = *libretsc::MetadataColumnGroupTable_GetShortName;
*GetDisplayOrder = *libretsc::MetadataColumnGroupTable_GetDisplayOrder;
*GetDisplayLength = *libretsc::MetadataColumnGroupTable_GetDisplayLength;
*GetDisplayHeight = *libretsc::MetadataColumnGroupTable_GetDisplayHeight;
*GetImmediateRefresh = *libretsc::MetadataColumnGroupTable_GetImmediateRefresh;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataColumnGroupTable(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataColumnGroupTable($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataColumnGroupTableList ##############

package librets::MetadataColumnGroupTableList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataColumnGroupTableList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataColumnGroupTableList_size;
*empty = *libretsc::MetadataColumnGroupTableList_empty;
*clear = *libretsc::MetadataColumnGroupTableList_clear;
*push = *libretsc::MetadataColumnGroupTableList_push;
*pop = *libretsc::MetadataColumnGroupTableList_pop;
*get = *libretsc::MetadataColumnGroupTableList_get;
*set = *libretsc::MetadataColumnGroupTableList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataColumnGroupTableList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataFilter ##############

package librets::MetadataFilter;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataFilter($self);
        delete $OWNER{$self};
    }
}

*GetMetadataType = *libretsc::MetadataFilter_GetMetadataType;
*GetID = *libretsc::MetadataFilter_GetID;
*GetFilterID = *libretsc::MetadataFilter_GetFilterID;
*GetParentResourceID = *libretsc::MetadataFilter_GetParentResourceID;
*GetParentLookupName = *libretsc::MetadataFilter_GetParentLookupName;
*GetChildResourceID = *libretsc::MetadataFilter_GetChildResourceID;
*GetChildLookupName = *libretsc::MetadataFilter_GetChildLookupName;
*GetNotShownByDefault = *libretsc::MetadataFilter_GetNotShownByDefault;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataFilter(@_);
    bless $self, $pkg if defined($self);
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataFilterList ##############

package librets::MetadataFilterList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataFilterList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataFilterList_size;
*empty = *libretsc::MetadataFilterList_empty;
*clear = *libretsc::MetadataFilterList_clear;
*push = *libretsc::MetadataFilterList_push;
*pop = *libretsc::MetadataFilterList_pop;
*get = *libretsc::MetadataFilterList_get;
*set = *libretsc::MetadataFilterList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataFilterList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataFilterType ##############

package librets::MetadataFilterType;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets::MetadataElement librets );
%OWNER = ();
%ITERATORS = ();
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataFilterType($self);
        delete $OWNER{$self};
    }
}

*GetMetadataType = *libretsc::MetadataFilterType_GetMetadataType;
*GetID = *libretsc::MetadataFilterType_GetID;
*GetFilterTypeID = *libretsc::MetadataFilterType_GetFilterTypeID;
*GetParentValue = *libretsc::MetadataFilterType_GetParentValue;
*GetChildValue = *libretsc::MetadataFilterType_GetChildValue;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataFilterType(@_);
    bless $self, $pkg if defined($self);
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::MetadataFilterTypeList ##############

package librets::MetadataFilterTypeList;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = libretsc::new_MetadataFilterTypeList(@_);
    bless $self, $pkg if defined($self);
}

*size = *libretsc::MetadataFilterTypeList_size;
*empty = *libretsc::MetadataFilterTypeList_empty;
*clear = *libretsc::MetadataFilterTypeList_clear;
*push = *libretsc::MetadataFilterTypeList_push;
*pop = *libretsc::MetadataFilterTypeList_pop;
*get = *libretsc::MetadataFilterTypeList_get;
*set = *libretsc::MetadataFilterTypeList_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_MetadataFilterTypeList($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::RetsMetadata ##############

package librets::RetsMetadata;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
*GetSystem = *libretsc::RetsMetadata_GetSystem;
*GetAllForeignKeys = *libretsc::RetsMetadata_GetAllForeignKeys;
*GetAllResources = *libretsc::RetsMetadata_GetAllResources;
*GetResource = *libretsc::RetsMetadata_GetResource;
*GetAllClasses = *libretsc::RetsMetadata_GetAllClasses;
*GetClass = *libretsc::RetsMetadata_GetClass;
*GetAllTables = *libretsc::RetsMetadata_GetAllTables;
*GetTable = *libretsc::RetsMetadata_GetTable;
*GetAllLookups = *libretsc::RetsMetadata_GetAllLookups;
*GetLookup = *libretsc::RetsMetadata_GetLookup;
*GetAllLookupTypes = *libretsc::RetsMetadata_GetAllLookupTypes;
*GetLookupType = *libretsc::RetsMetadata_GetLookupType;
*GetAllObjects = *libretsc::RetsMetadata_GetAllObjects;
*GetSearchHelp = *libretsc::RetsMetadata_GetSearchHelp;
*GetAllColumnGroups = *libretsc::RetsMetadata_GetAllColumnGroups;
*GetAllColumnGroupSets = *libretsc::RetsMetadata_GetAllColumnGroupSets;
*GetAllColumnGroupControls = *libretsc::RetsMetadata_GetAllColumnGroupControls;
*GetAllColumnGroupTables = *libretsc::RetsMetadata_GetAllColumnGroupTables;
*GetAllColumnGroupNormalizations = *libretsc::RetsMetadata_GetAllColumnGroupNormalizations;
*GetAllFilters = *libretsc::RetsMetadata_GetAllFilters;
*GetAllFilterTypes = *libretsc::RetsMetadata_GetAllFilterTypes;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::RetsHttpLogger ##############

package librets::RetsHttpLogger;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
*RECEIVED = *libretsc::RetsHttpLogger_RECEIVED;
*SENT = *libretsc::RetsHttpLogger_SENT;
*INFORMATIONAL = *libretsc::RetsHttpLogger_INFORMATIONAL;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_RetsHttpLogger($self);
        delete $OWNER{$self};
    }
}

*logHttpData = *libretsc::RetsHttpLogger_logHttpData;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : librets::RetsSession ##############

package librets::RetsSession;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( librets );
%OWNER = ();
%ITERATORS = ();
*MODE_CACHE = *libretsc::RetsSession_MODE_CACHE;
*MODE_CACHE = *libretsc::RetsSession_MODE_CACHE;
*MODE_NO_STREAM = *libretsc::RetsSession_MODE_NO_STREAM;
*MODE_NO_STREAM = *libretsc::RetsSession_MODE_NO_STREAM;
*MODE_NO_EXPECT = *libretsc::RetsSession_MODE_NO_EXPECT;
*MODE_NO_EXPECT = *libretsc::RetsSession_MODE_NO_EXPECT;
*MODE_NO_SSL_VERIFY = *libretsc::RetsSession_MODE_NO_SSL_VERIFY;
*MODE_NO_SSL_VERIFY = *libretsc::RetsSession_MODE_NO_SSL_VERIFY;
sub new {
    my $pkg = shift;
    my $self = libretsc::new_RetsSession(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        libretsc::delete_RetsSession($self);
        delete $OWNER{$self};
    }
}

*GetLoginUrl = *libretsc::RetsSession_GetLoginUrl;
*Login = *libretsc::RetsSession_Login;
*GetLoginResponse = *libretsc::RetsSession_GetLoginResponse;
*GetCapabilityUrls = *libretsc::RetsSession_GetCapabilityUrls;
*GetAction = *libretsc::RetsSession_GetAction;
*CreateSearchRequest = *libretsc::RetsSession_CreateSearchRequest;
*Search = *libretsc::RetsSession_Search;
*Logout = *libretsc::RetsSession_Logout;
*GetMetadata = *libretsc::RetsSession_GetMetadata;
*IsIncrementalMetadata = *libretsc::RetsSession_IsIncrementalMetadata;
*SetIncrementalMetadata = *libretsc::RetsSession_SetIncrementalMetadata;
*GetObject = *libretsc::RetsSession_GetObject;
*SetUserAgent = *libretsc::RetsSession_SetUserAgent;
*UseHttpGet = *libretsc::RetsSession_UseHttpGet;
*SetRetsVersion = *libretsc::RetsSession_SetRetsVersion;
*GetRetsVersion = *libretsc::RetsSession_GetRetsVersion;
*GetDetectedRetsVersion = *libretsc::RetsSession_GetDetectedRetsVersion;
*RetsVersionToString = *libretsc::RetsSession_RetsVersionToString;
*SetHttpLogger = *libretsc::RetsSession_SetHttpLogger;
*SetUserAgentAuthType = *libretsc::RetsSession_SetUserAgentAuthType;
*GetUserAgentAuthType = *libretsc::RetsSession_GetUserAgentAuthType;
*SetUserAgentPassword = *libretsc::RetsSession_SetUserAgentPassword;
*SetDefaultEncoding = *libretsc::RetsSession_SetDefaultEncoding;
*Cleanup = *libretsc::RetsSession_Cleanup;
*SetLogEverything = *libretsc::RetsSession_SetLogEverything;
*SetModeFlags = *libretsc::RetsSession_SetModeFlags;
*GetLibraryVersion = *libretsc::RetsSession_GetLibraryVersion;
*SetProxy = *libretsc::RetsSession_SetProxy;
*SetHttpLogName = *libretsc::RetsSession_SetHttpLogName;
*SetTimeout = *libretsc::RetsSession_SetTimeout;
*CreateUpdateRequest = *libretsc::RetsSession_CreateUpdateRequest;
*Update = *libretsc::RetsSession_Update;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package librets;

*GetObjectRequest_PHOTO_TYPE = *libretsc::GetObjectRequest_PHOTO_TYPE;
*GetObjectRequest_PLAT_TYPE = *libretsc::GetObjectRequest_PLAT_TYPE;
*GetObjectRequest_VIDEO_TYPE = *libretsc::GetObjectRequest_VIDEO_TYPE;
*GetObjectRequest_AUDIO_TYPE = *libretsc::GetObjectRequest_AUDIO_TYPE;
*GetObjectRequest_THUMBNAIL_TYPE = *libretsc::GetObjectRequest_THUMBNAIL_TYPE;
*GetObjectRequest_MAP_TYPE = *libretsc::GetObjectRequest_MAP_TYPE;
*GetObjectRequest_VRIMAGE_TYPE = *libretsc::GetObjectRequest_VRIMAGE_TYPE;
*RETS_1_0 = *libretsc::RETS_1_0;
*RETS_1_5 = *libretsc::RETS_1_5;
*RETS_1_7 = *libretsc::RETS_1_7;
*RETS_1_7_2 = *libretsc::RETS_1_7_2;
*RETS_1_8 = *libretsc::RETS_1_8;
*RETS_1_8_0 = *libretsc::RETS_1_8_0;
*RETS_XML_DEFAULT_ENCODING = *libretsc::RETS_XML_DEFAULT_ENCODING;
*RETS_XML_ISO_ENCODING = *libretsc::RETS_XML_ISO_ENCODING;
*RETS_XML_UTF8_ENCODING = *libretsc::RETS_XML_UTF8_ENCODING;
*USER_AGENT_AUTH_RETS_1_7 = *libretsc::USER_AGENT_AUTH_RETS_1_7;
*USER_AGENT_AUTH_INTEREALTY = *libretsc::USER_AGENT_AUTH_INTEREALTY;
1;
